project:
  type: website
  output-dir: _site/

website:
  favicon: favicon.webp
  open-graph: true
  site-url: https://ai-sic.github.io
  navbar:
    search: true
    logo: images/logo.png
    logo-alt: "logo"
    title: ""
    collapse-below: xl
    right:
      - text: articles
        href: articles/index.qmd
      - text: about
        href: about.qmd
      #- text: participation
       # href: participation.qmd
      - text: contact
        href: contact.qmd
      - text: de
        href: ../de
      - text: en
        href: ./
  page-navigation: true
  back-to-top-navigation: false
  page-footer:
    center:
      - href: https://github.com/AI-SIC
        icon: github
        aria-label: GitHub
      - href: imprint.html
        text: Imprint
      - href: privacy-statement.html
        text: Privacy Statement
    left: |
      <div style="display:flex; align-items:center; gap:12px;">
      <div>
      <a href="https://www.new-data-spaces.de/en-us/Start/Projects/AI-SIC">
         <img src="/images/Logo_NewDataSpaces_RGB.png" height="40">
      </a>
      </div>
      <div>
      <a href="https://www.dfg.de/en">
          <img src="/images/dfg_logo_schriftzug_blau_foerderung_en.jpg" height="40" style="margin-left:10px;">
      </a>
      </div>
      <div>
      <p>
          © 2026 AI-SIC
      </p>
      </div>
      </div>
    right:
      - text: "Built with Quarto, inspired by martenw.com"

metadata:
  description: >
    AI Enhanced Validation of Survey Instruments: Integrating Semi-Automated Methods in Cognitive Interviews for Children’s Self- and Proxy-Assessments of Health


format:
  html:
    theme: [aisic-custom.scss]
    toc: true
    grid:
      body-width: 800px
    html-math-method: katex
    include-in-header: 
      text: |
        <script type="application/ld+json"> # JSON-LD for SEO
        {
          "@context": "https://schema.org/",
          "@type": "Organization",
          "name": "AI-SIC",
          "url": "https://ai-sic.github.io",
          "alternateName": "AI Enhanced Validation of Survey Instruments",
          "description": "Research Project",
          "image": "",
          "sameAs": [
             "https://ai-sic.github.io"
          ],
        }
        </script>


#for transparency in plots in ggplot! see in Test 
knitr: 
  opts_chunk:
    dev: svg
    dev.args: { bg: "transparent" }

link-external-icon: false
link-external-newwindow: true

execute: 
  freeze: auto

