project:
  type: website
  output-dir: _site/de/

website:
  favicon: ../favicon.webp
  open-graph: true
  site-url: https://ai-sic.github.io/de
  navbar:
    logo: /images/logo.png
    logo-alt: "logo"
    title: ""
    collapse-below: lg
    right:
      - text: artikel
        href: de/articles/index.qmd
      - text: über uns
        href: de/about.qmd
      - text: kontakt
        href: de/contact.qmd
      - text: de
        href: de/
      - text: en
        href: ../
  page-navigation: true
  back-to-top-navigation: false
  page-footer:
    center:
      - href: https://github.com/AI-SIC
        icon: github
        aria-label: GitHub
      - href: /imprint.html
        text: Impressum
      - href: /privacy-statement.html
        text: Datenschutzerklärung
    left: |
      <div style="display:flex; align-items:center; gap:12px;">
      <div>
      <a href="https://www.new-data-spaces.de/en-us/Start/Projects/AI-SIC">
         <img src="images/Logo_NewDataSpaces_RGB.png" height="40">
      </a>
      </div>
      <div>
      <a href="https://www.dfg.de/en">
          <img src="images/dfg_logo_schriftzug_blau_foerderung_en.jpg" height="40" style="margin-left:10px;">
      </a>
      </div>
      <div>
      <p>
          © 2025 AI-SIC
      </p>
      </div>
      </div>
    right:
      - text: "Erstellt mit Quarto. Vorlage von martenw.com"

format:
  html:
    lang: de-DE
    theme: [aisic-custom.scss]
    toc: true
    grid:
      body-width: 800px
    html-math-method: katex
    include-in-header: 
      text: |
        <script type="application/ld+json">
        {
          "@context": "https://schema.org/",
          "@type": "Organization",
          "name": "AI-SIC",
          "url": "https://ai-sic.github.io",
          "alternateName": "KI-gestützte Validierung von Fragebögen",
          "description": "Forschungsprojekt",
          "sameAs": [
            "https://ai-sic.github.io"
          ]
        }
        </script>
